"use client";

import { useRef, useState } from "react";
import type { demoScan } from "@/lib/odds/demo";
import { OUTCOMES, type ArbitrageOpportunity, type OddsMode, type ProviderError, type ProviderUsage, type ScanAnalysis } from "@/lib/odds/types";
import type { Discovery, ScanQuote } from "@/lib/odds/server/service";
import ResearchHeader from "../research-header";
import shared from "../scanner-dashboard.module.css";
import styles from "./odds.module.css";

type Scan = ReturnType<typeof demoScan> & { usage?: ProviderUsage; unchanged?: boolean };
type EventPage = { events: { id: string; competition: string; home: string | null; away: string | null; kickoff: string | null; status: string; coverage: string[] }[]; cursor: string | null };
const percent = (value: number) => `${(value * 100).toFixed(2)}%`;
const tokens = (value: ProviderUsage["remaining"]) => value === null ? "Unknown" : value === "unlimited" ? "Unlimited" : value.toLocaleString("en-GB");
const time = (value: string | null) => value === null ? "Unknown" : value.replace("T", " ").replace("Z", " UTC");
function TheoreticalOpportunity({ opportunity: a, rank }: { opportunity: ArbitrageOpportunity; rank: number }) {
  return <article className={styles.opportunity}>
    <div className={styles.opportunityHeading}><div><span className={shared.eyebrow}>#{rank} / THEORETICAL · BEFORE COSTS</span><h3>{a.fixture.homeTeam} vs {a.fixture.awayTeam}</h3><p>{a.fixture.competition} · {time(a.fixture.kickoff)}</p></div><div><span className={shared.eyebrow}>Theoretical gross ROI</span><strong className={styles.roi}>{percent(a.theoreticalGrossROI)}</strong></div></div>
    <div className={styles.legs}>{OUTCOMES.map((outcome) => <div key={outcome}><span className={shared.eyebrow}>{outcome}</span><strong>{a.selections[outcome].decimalOdds.toFixed(3)}</strong><span>{a.selections[outcome].bookmaker.name}</span><small>Venue/sport evidence: {time(a.selections[outcome].evidenceAt)}</small></div>)}</div>
    <p className={styles.formula}>S = {a.inverseOddsSum.toFixed(8)} · gross ROI = 1/S − 1</p>
    <details><summary>Illustrative fractions and equalized gross payout</summary><p>Education only: HOME {percent(a.illustrativeFractions.HOME)}, DRAW {percent(a.illustrativeFractions.DRAW)}, AWAY {percent(a.illustrativeFractions.AWAY)}. Before display rounding, fractions sum to one and each outcome returns {a.grossPayoutPerUnit.toFixed(8)} units per illustrative total unit. This is not a stake recommendation or execution facility.</p></details>
    <p className={styles.caution}>Not executable or guaranteed. Prices can move; bookmaker limits, acceptance, settlement terms and costs still need independent verification.</p>
  </article>;
}
function Results({ analysis, mode, unchanged }: { analysis: ScanAnalysis; mode: OddsMode; unchanged?: boolean }) {
  return <section id="odds-results" aria-labelledby="results-title">
    <div className={shared.sectionHeading}><div><p className={shared.eyebrow}>{mode === "DEMO" ? "SYNTHETIC DEMONSTRATION RESULTS" : "ODDSRELAY SOURCE RESULTS"}</p><h2 id="results-title">{analysis.status}</h2></div><span className={shared.sortLabel}>Gross ROI ↓ · freshness · event ID</span></div>
    <p className={styles.muted}>Evaluated {time(analysis.evaluatedAt)}. {unchanged && "Unchanged provider response (304); original freshness evidence was retained and rechecked."} Results are a snapshot; use an explicit action to reevaluate.</p>
    {!analysis.opportunities.length && <div className={shared.emptyState}><h3>NO VERIFIED OPPORTUNITY</h3><p>{analysis.status === "INSUFFICIENT DATA" ? "Eligible coverage is insufficient. Missing or stale prices are excluded." : "Complete eligible markets do not have an inverse-odds sum below one."}</p></div>}
    {analysis.opportunities.map((a, i) => <TheoreticalOpportunity key={a.fixture.id} opportunity={a} rank={i + 1} />)}
    <div className={shared.rankingPanel}><div className={shared.rankingHeading}><h3>All fixture comparisons</h3><p>Full-time 1X2 · bookmaker back offers only · decimal odds</p></div>
      <div className={shared.tableScroll} role="region" aria-label="Fixture price comparisons" tabIndex={0}><table className={`${shared.table} ${styles.table}`}><caption className={shared.srOnly}>Best eligible HOME, DRAW and AWAY bookmaker prices, with exclusions and comparison status.</caption><thead><tr><th scope="col">Fixture / UTC kickoff</th>{OUTCOMES.map((o) => <th key={o} scope="col">{o} / bookmaker</th>)}<th scope="col">S / status</th></tr></thead><tbody>{analysis.markets.map((r) => <tr key={r.fixture.id}><th scope="row">{r.fixture.homeTeam} vs {r.fixture.awayTeam}<span>{r.fixture.competition}</span><span>{time(r.fixture.kickoff)}</span></th>{OUTCOMES.map((o) => <td key={o}>{r.best[o] ? <><strong>{r.best[o]!.decimalOdds.toFixed(3)}</strong><span>{r.best[o]!.bookmaker.name}</span><small>{time(r.best[o]!.evidenceAt)}</small></> : "Excluded / missing"}</td>)}<td>{r.inverseOddsSum?.toFixed(8) ?? "—"}<span>{r.status}</span>{r.reasons.map((reason) => <small key={reason}>{reason}</small>)}</td></tr>)}</tbody></table></div>
    </div>
    <details className={styles.exclusions}><summary>Excluded data ({analysis.excluded.length})</summary>{analysis.excluded.length ? <ul>{analysis.excluded.map((r, i) => <li key={`${r.source}:${i}`}><strong>{r.eventId ?? "Unknown event"}</strong>: {r.reason}<small>Source reference: {r.source}</small></li>)}</ul> : <p>No source rows were excluded.</p>}</details>
  </section>;
}
export default function OddsDashboard({ configured, initialDemo }: { configured: boolean; initialDemo: ReturnType<typeof demoScan> }) {
  const [mode, setMode] = useState<OddsMode>("DEMO"), [scan, setScan] = useState<Scan | null>(initialDemo);
  const [discovery, setDiscovery] = useState<Discovery | null>(null), [selected, setSelected] = useState<string[]>([]), [quote, setQuote] = useState<ScanQuote | null>(null);
  const [usage, setUsage] = useState<ProviderUsage | null>(null), [error, setError] = useState<ProviderError | null>(null), [busy, setBusy] = useState("");
  const [acknowledged, setAcknowledged] = useState(false), [events, setEvents] = useState<EventPage | null>(null), [pricing, setPricing] = useState<string | null>(null);
  const inFlight = useRef(false);
  async function action<T>(name: string, extra: Record<string, unknown> = {}): Promise<T | null> {
    if (inFlight.current) return null;
    inFlight.current = true; setBusy(name); setError(null);
    try {
      const response = await fetch("/api/odds", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "same-origin", cache: "no-store", body: JSON.stringify({ action: name, mode, ...extra }) });
      const result = await response.json();
      if (!response.ok) { setError(result.error); if (result.error?.usage) setUsage(result.error.usage); return null; }
      if (result.usage) setUsage(result.usage);
      return result as T;
    } catch { setError({ code: "LOCAL_NETWORK_ERROR", status: 502, retryAfter: null, message: "The local request failed. Do not retry confirmation; obtain a new free quote. Token use may be uncertain." }); return null; }
    finally { inFlight.current = false; setBusy(""); }
  }
  function changeMode(next: OddsMode) { setMode(next); setScan(next === "DEMO" ? initialDemo : null); setQuote(null); setError(null); setAcknowledged(false); }
  async function discover() { setQuote(null); setSelected([]); const result = await action<Discovery>("discover"); if (result) { setDiscovery(result); setUsage(result.usage); setSelected(result.bookmakers.filter((b) => b.eligible).slice(0, 2).map((b) => b.id)); } }
  async function getQuote() { setQuote(null); setAcknowledged(false); const result = await action<ScanQuote>("quote", { bookmakers: selected }); if (result) { setQuote(result); setUsage(result.usage); } }
  async function confirm() {
    if (!quote?.approvalId || !acknowledged) return;
    const approval = quote; setQuote(null); setScan(null); // consumed locally before awaiting, even on failure
    const result = await action<Scan>("confirm", { approvalId: approval.approvalId, bookmakers: approval.request.bookmakers });
    if (result) { setScan(result); setUsage(result.usage ?? null); }
  }
  function selectBookmaker(id: string) { setQuote(null); setSelected((previous) => previous.includes(id) ? previous.filter((b) => b !== id) : [...previous, id]); }
  return <div className={shared.shell}><a href="#odds-results" className={shared.skipLink}>Skip to odds results</a><ResearchHeader activePage="odds" /><main className={shared.main}>
    <div className={shared.pageHeading}><div><p className={shared.eyebrow}>FOOTBALL / FULL-TIME 1X2</p><h1>Odds Scanner<span className={shared.titleDot}>.</span></h1><p className={shared.intro}>Compare offered prices. Check theoretical arbitrage.</p></div><span className={shared.datasetTag}>{mode === "DEMO" ? "DEMO / ALL ODDS SYNTHETIC" : "LIVE SOURCE / ODDSRELAY"}</span></div>
    <div className={shared.simulationNotice}><span className={shared.noticeIcon} aria-hidden="true">i</span><p>{mode === "DEMO" ? "All demonstration teams, bookmakers and prices are synthetic. Offline demo spends zero API tokens; these prices are not currently available." : "On-demand research only. No live request runs on page load. Source freshness does not guarantee bookmaker execution. No winning-probability estimate, value model or bet placement."}</p></div>
    <section className={styles.controls} aria-label="Mode and provider configuration"><div className={styles.modeSwitch}><button type="button" onClick={() => changeMode("DEMO")} disabled={Boolean(busy)} aria-pressed={mode === "DEMO"}>DEMO</button><button type="button" onClick={() => changeMode("LIVE")} disabled={Boolean(busy)} aria-pressed={mode === "LIVE"}>LIVE SOURCE</button></div><dl className={styles.meta}><div><dt>API configuration</dt><dd>{configured ? discovery ? "Server key configured · discovery checked" : "Server key configured · access unverified" : "No key configured · DEMO ready"}</dd></div><div><dt>Remaining tokens</dt><dd>{usage ? tokens(usage.remaining) : "Unknown · no account request yet"}</dd></div><div><dt>Scan guardrail</dt><dd>Maximum 500 tokens / confirmed scan</dd></div></dl></section>
    {mode === "DEMO" ? <div className={styles.demoControls}><p>Four synthetic fixtures: arbitrage, ordinary prices, a missing draw and stale evidence.</p><button className={shared.applyButton} type="button" disabled={Boolean(busy)} onClick={async () => { const result = await action<Scan>("demo"); if (result) setScan(result); }}>Re-run synthetic demo · zero tokens</button></div> : <>
      {!configured && <div className={styles.notice} role="status">Add ODDSRELAY_KEY to your gitignored .env.local and restart the app. Live controls require server configuration; never paste the key into this page.</div>}
      <section className={styles.controls} aria-labelledby="provider-discovery"><h2 id="provider-discovery">Verify account and bookmaker coverage</h2><p>Your stated account allowance is 2,500 tokens/month. The actual balance and limits below come from authenticated usage, not a hardcoded allowance. Global bookmaker listings do not establish access; each free quote validates the selected request.</p><div className={styles.actions}><button className={shared.applyButton} type="button" disabled={!configured || Boolean(busy)} onClick={discover}>Refresh discovery · free</button><button className={shared.resetButton} type="button" disabled={!configured || Boolean(busy)} onClick={async () => { const result = await action<{ rateCard: string; regions: unknown; usage: ProviderUsage }>("pricing"); if (result) { setPricing(JSON.stringify({ rateCard: result.rateCard, regions: result.regions }, null, 2)); } }}>View pricing · free</button><button className={shared.resetButton} type="button" disabled={!configured || Boolean(busy)} onClick={async () => { const result = await action<EventPage>("events"); if (result) setEvents(result); }}>List football events · free</button></div>
        {discovery && <><p>Plan: {discovery.plan ?? "unknown"} · {discovery.competitionCount} verified football competitions · discovery {time(discovery.capturedAt)}. Refresh discovery if older than 60 seconds.</p>{discovery.restrictions.map((r) => <p key={r} className={styles.warning}>{r}</p>)}<fieldset className={styles.bookmakers}><legend>Select two or three fresh covered bookmakers</legend>{discovery.bookmakers.map((b) => <label key={b.id}><input type="checkbox" checked={selected.includes(b.id)} disabled={Boolean(busy) || !b.eligible || (!selected.includes(b.id) && selected.length >= 3)} onChange={() => selectBookmaker(b.id)} /><span><strong>{b.name}</strong><small>{b.eligible ? `${b.events} soccer events · evidence ${time(b.lastSeen)} · quote checks access` : b.reason}</small></span></label>)}</fieldset></>}
        <button className={shared.applyButton} type="button" disabled={!configured || Boolean(busy) || selected.length < 2 || selected.length > 3} onClick={getQuote}>Get quote · free</button>
      </section>
      {quote && <section className={styles.quote} aria-labelledby="quote-title"><h2 id="quote-title">Review the exact scan</h2><p>UK · soccer · h2h · {quote.request.bookmakers.join(", ")}</p><dl className={styles.meta}><div><dt>Quoted token cost</dt><dd>{quote.cost}</dd></div><div><dt>Remaining before scan</dt><dd>{tokens(quote.usage.remaining)}</dd></div><div><dt>Projected remaining</dt><dd>{tokens(quote.projectedRemaining)}</dd></div><div><dt>Allowance reset</dt><dd>{time(quote.usage.resetsAt)}</dd></div><div><dt>Approval expires</dt><dd>{time(quote.expiresAt)}</dd></div></dl>{quote.blocked.map((reason) => <p key={reason} className={styles.warning}>{reason}</p>)}
        {quote.approvalId && <><label className={styles.acknowledgement}><input type="checkbox" checked={acknowledged} disabled={Boolean(busy)} onChange={(e) => setAcknowledged(e.target.checked)} /><span>I understand this single scan can spend {quote.cost} API tokens. Prices may be unavailable or move; theoretical arbitrage is not guaranteed profit.</span></label><button className={shared.applyButton} type="button" disabled={Boolean(busy) || !acknowledged} onClick={confirm}>Confirm Scan · up to {quote.cost} tokens</button></>}
      </section>}
      {pricing && <details className={styles.exclusions} open><summary>Provider pricing table</summary><pre className={styles.pricing}>{pricing}</pre></details>}
      {events && <details className={styles.exclusions} open><summary>Discovered events ({events.events.length} on this page)</summary><ul>{events.events.map((e, i) => <li key={`${e.id}:${i}`}>{e.home ?? "Unsplit fixture"} vs {e.away ?? "Unknown"} · {e.competition} · {time(e.kickoff)} · {e.status} · coverage {e.coverage.join(", ")}</li>)}</ul>{events.cursor && <button className={shared.resetButton} type="button" disabled={Boolean(busy)} onClick={async () => { const result = await action<EventPage>("events", { cursor: events.cursor }); if (result) setEvents(result); }}>Next event page · free</button>}<p>Discovery is not offered-price evidence. No fixture joining uses this event list.</p></details>}
    </>}
    {busy && <p role="status">{busy === "confirm" ? "One confirmed scan is in progress. Do not resubmit." : "Processing explicit action…"}</p>}
    {error && <div className={styles.error} role="alert"><strong>{error.code}</strong><p>{error.message}</p>{error.retryAfter && <p>Retry-After: {error.retryAfter}. No automatic retry or polling.</p>}{error.usage && <p>Actual error-response usage: cost {error.usage.cost ?? "unknown"} · used {error.usage.used ?? "unknown"} · remaining {tokens(error.usage.remaining)} · limit {tokens(error.usage.limit)} · reset {time(error.usage.resetsAt)}</p>}</div>}
    {mode === "LIVE" && scan?.usage && <div className={styles.notice}><strong>Actual provider response usage</strong><p>Cost: {scan.usage.cost ?? "unknown"} · used: {scan.usage.used ?? "unknown"} · remaining: {tokens(scan.usage.remaining)} · limit: {tokens(scan.usage.limit)} · reset: {time(scan.usage.resetsAt)}</p><p>Optional headers remain unknown when absent. Quoted cost is not substituted for actual cost.</p></div>}
    {scan ? <Results analysis={scan.analysis} mode={mode} unchanged={scan.unchanged} /> : <section id="odds-results" className={shared.emptyState}><h2>No live scan requested</h2><p>Refresh free discovery, select a small bookmaker subset, obtain a free quote, then explicitly confirm that exact scan.</p></section>}
    <section className={shared.methodology}><div className={shared.methodHeading}><h2>How this scanner works</h2><p>Offered prices only · research before execution</p></div><div className={shared.methodGrid}><div><h3>One fixture, one settlement</h3><p>Exact provider event and competition identities, standard football h2h and HOME/Draw/AWAY outcomes. No fuzzy joins, two-way markets, exchange lays or raw-board fallbacks.</p></div><div><h3>Fresh evidence</h3><p>Venue/sport last-seen metadata must be within 120 seconds. Missing/future evidence, unavailable prices and started fixtures are excluded. Receipt time is never treated as bookmaker price time.</p></div><div><h3>Theoretical comparison</h3><p>Best eligible HOME, DRAW and AWAY prices across verified bookmakers. S = 1/H + 1/D + 1/A. S &lt; 1 gives theoretical gross ROI = 1/S − 1, before costs and price movement.</p></div><div><h3>Manual token approval</h3><p>Free quote first; exact server approval expires after 60 seconds and is consumed once. No timer, automatic refresh, chargeable retry, bet placement, probability model or bankroll feature.</p></div></div></section>
    <footer className={shared.footer}><span>BET SCANNER / ODDS RESEARCH</span><span>V1.0 · manual scans only</span></footer>
  </main></div>;
}
