import dataset from "./generated/epl-seasons.json";
import provenance from "../../data/external/openfootball/provenance.json";
import type { HistoricalSeason } from "../lib/backtest/types";

// Generated by pnpm data:build; loaded locally, never acquired at runtime.
export const eplSeasons: readonly HistoricalSeason[] = dataset as readonly HistoricalSeason[];
export const eplProvenance = provenance;
